# 🍨 Support scoop development
# These are supported funding model platforms

# GitHub Sponsors (if enabled)
# github: [ai-screams]

# Buy Me a Coffee
buy_me_a_coffee: pignuante

# Other platforms (uncomment if needed)
# ko_fi: username
# patreon: username
# open_collective: scoop-uv
# custom: ["https://your-link.com"]
